

version: 2.1
description: |
  CircleCI Config for Cucumber Extended Sublime Text 3 Plugin

jobs:
  say_hello:
    working_directory: ~/sublime-cucumber-extended
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          keys:
            - '{{ $CIRCLE_TAG }}-yarn-{{ .Branch }}-{{ checksum "yarn.lock" }}'
            - '{{ $CIRCLE_TAG }}-yarn-{{ .Branch }}-'
            - '{{ $CIRCLE_TAG }}-yarn-'
            - '-yarn-{{ .Branch }}-{{ checksum "yarn.lock" }}'
            - '-yarn-{{ .Branch }}-'
            - '-yarn-'

      - run:
          name: Running Yarn Install
          command: yarn install

      - save_cache:
          keys:
            - '{{ $CIRCLE_TAG }}-yarn-{{ .Branch }}-{{ checksum "yarn.lock" }}'
            - '-yarn-{{ .Branch }}-{{ checksum "yarn.lock" }}'
          paths:
            - ~/.cache/yarn

workflows:
  version: 2.1
  hello_world:
    jobs:
      - say_hello
