

version: 2.1
description: |
  CircleCI Config for Cucumber Extended Sublime Text 3 Plugin

jobs:
  say_hello:
    working_directory: ~/sublime-cucumber-extended
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Saying Hello to the World
          command: echo "Hello World"

workflows:
  version: 2.1
  hello_world:
    jobs:
      - say_hello
